name: R-CMD-check

on:
  push:
    branches: [main, master, code_refactor]
  pull_request:
    branches: [main, master, code_refactor]

jobs:
  R-CMD-check:
    matrix:
      config:
        - {os: ubuntu-latest, r: 'release'}
        - {os: ubuntu-latest, r: '4.4.0'}
        - {os: ubuntu-latest, r: '4.1.0'}
        - {os: ubuntu-latest, r: '3.5.0'}
        - {os: windows-latest, r: 'release'}
        - {os: windows-latest, r: '4.4.0'}
        - {os: windows-latest, r: '4.1.0'}
        - {os: windows-latest, r: '3.5.0'}
        
    runs-on: ${{ matrix.confiig.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install package dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Install system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            testthat
            covr
            rcmdcheck
          needs: |
            # List any needed system libraries here (e.g. libcurl4-openssl-dev)

      - name: Check R package
        uses: r-lib/actions/check-r-package@v2

      - name: Upload Check Results
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results-${{ matrix.config.os }}-R-${{ matrix.config.r }}
          path: check
